local_backend: true
backend:
  site_domain: cms.netlify.com
  name: git-gateway
  branch: master
media_folder: "images/uploads"
publish_mode: editorial_workflow
collections:
  - name: 'article'
    label: 'Article'
    folder: '_posts/article'
    create: true
    slug: "{{slug}}"
    fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}